### ISSUE TITLE
atal error: Can't use function return value in write context in D:\phpStudy\PHPTutorial\WWW\includes\classes\ia.core.users.php on line 567

### ISSUE THREAD

**Issue by jiasicms** [intelliants/subrion#681] opened 2018-04-10 00:58 UTC
atal error: Can't use function return value in write context in D:\phpStudy\PHPTutorial\WWW\includes\classes\ia.core.users.php on line 567

$password = password_hash($rawPassword, PASSWORD_BCRYPT);

no password_hash

**Comment by 4unkur** [comment] 2018-04-10 03:34
Hello @jiasicms,

Please let us know which version of the script do you use and what are the steps to reproduce this issue as in the latest stable and development versions of the script this issue doesn't occur.

Thank you.

**Comment by jiasicms** [comment] 2018-04-12 03:04
4.2.0

**Comment by vbezruchkin** [comment] 2018-04-12 04:32
Hi,

I believe the issue is related to an obsolete version of PHP, not Subrion itself @4unkur 

password_hash function is implemented in php 5.5+ ((PHP 5 >= 5.5.0, PHP 7)) and it looks like @jiasicms uses an older one.

@jiasicms please update your php version and I'm sure the problem will disappear.

Cheers

**Comment by Batry** [comment] 2018-04-12 04:59
Here is the line 567 in my distro:
```
567                if ($plan['id'] && empty(floatval($plan['cost']))) {
568                    $iaPlan->assignFreePlan($plan['id'], self::getItemName(), $member);
569                }
```

I suppose combining `empty` with `floatval` maybe generating the issue.

**Comment by jiasicms** [comment] 2018-04-12 06:58
Yes, my php version is 5.4.
Thanks!

**Comment by vbezruchkin** [comment] 2018-04-12 07:35
Ok, we highly recommend to upgrade your version to 7.x. Closing the task.

**Closed by vbezruchkin** 2018-04-12 07:35 UTC
