### ISSUE TITLE
Cars for sale by bodystyle

### ISSUE THREAD

**Issue by BuggeD88** [intelliants/subrion#770] opened 2018-07-30 14:40 UTC
Hello.

Links for block "Cars for sale by bodystyle" for autos package, any template is not working... Link is body:pickup/, body:sedan/, body:off-road/...

![screenshot_2](https://user-images.githubusercontent.com/25355068/43404156-1f2c8ce2-9417-11e8-9848-fa4d0e0afe09.png)

![screenshot_1](https://user-images.githubusercontent.com/25355068/43404159-2149779c-9417-11e8-8a27-9a9162830577.png)

**Comment by vbezruchkin** [comment] 2018-07-30 15:48
Hi

Please confirm you installed autos package before using this template. Thanks

**Comment by FoockeD** [comment] 2018-07-31 13:58
It does not work how ever I install it... WAMP, LAMP, with or without cloudflare... SSL or without... PHP 7.2.8 and 5.6.37


![2](https://user-images.githubusercontent.com/25355068/43464129-8c46615e-94da-11e8-9dca-84e5ab58d13c.png)
![1](https://user-images.githubusercontent.com/25355068/43464130-8c67428e-94da-11e8-91b8-813d642e445d.png)

**Comment by 4unkur** [comment] 2018-07-31 14:34
Hello,

This template requires Subrion CMS' Autos package to be installed: https://subrion.org/package/autos.html

Please confirm you have this package installed in your website.

If you have this package installed and still have this issue then please submit a ticket to our Help Desk: https://subrion.org/desk/
with admin panel URL and FTP credentials. We'll investigate this issue on your server.

Thanks.

**Comment by vbezruchkin** [comment] 2018-08-01 02:13
Thanks for your request. We have your ticket, the issue is confirmed. We will recheck it and fix.

**Comment by 4unkur** [comment] 2018-08-01 04:39
Problem resolved via helpdesk system

**Closed by 4unkur** 2018-08-01 04:39 UTC
Labels: critical
