### ISSUE TITLE
Fields aren't updated during package upgrade process

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#180] opened 2016-06-09 05:24 UTC
If I change any field, for example in the Real Estate package -> Property Type -> add new value and I change version of package from 4.0.x to 4.0.x+1, then this field will not be updated during package upgrade process.

**Comment by 4unkur** [comment] 2016-09-26 06:00
Duplicate of https://github.com/intelliants/subrion/issues/123

**Closed by 4unkur** 2016-09-26 06:00 UTC
Labels: bug
