### ISSUE TITLE
Strange behavior in plugin's install.xml file parsing process

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion#112] opened 2016-02-05 10:56 UTC
If I have the following structure in plugin's install.xml file:

```
...
<upgrade>
...
</upgrade>
<uninstall>
...
</uninstall>
```

then Uninstall instructions will be executed first. So during plugin upgrade process all the data (including plugin tables) will be removed.

And if I have the following structure:

```
...
<uninstall>
...
</uninstall>
<upgrade>
...
</upgrade>
```

upgrade plugin process works fine.

**Comment by Batry** [comment] 2017-01-17 10:12
Can't reproduce

**Comment by vbezruchkin** [comment] 2017-01-17 10:35
Agree. Does not look proper. Anyhow, it's recommended to stick to a common structure.  Closing this one.

**Closed by vbezruchkin** 2017-01-17 10:35 UTC
Labels: bug
