### ISSUE TITLE
4.1.2 Search is blank page. 

### ISSUE THREAD

**Issue by CKENT0369** [intelliants/subrion#411] opened 2017-03-27 10:36 UTC
Searching anything yields a blank page. Tried to debug. its just blank

**Comment by Batry** [comment] 2017-03-27 10:40
@CKENT0369, do you have debug mode enabled? it would allow to see the error message.

**Comment by CKENT0369** [comment] 2017-03-27 22:14
Even using debug, it shows nothing, debug doesnt even show in the corner

**Comment by vbezruchkin** [comment] 2017-03-28 01:32
Hi @CKENT0369 
Do you have it online? We would need access to the files in your installation as we cannot reproduce the problem on our installation. Or let us know the exact list of modules you have installed.

Thanks

**Comment by vbezruchkin** [comment] 2017-03-30 10:26
Hi,

I enabled full debug mode on your website, and that error happens due to banner plugin. It's not working good yet. I will create a new report, and close this ticket as the problem relates to banner plugin rather subrion core itself.

Thanks for your report.

**Closed by vbezruchkin** 2017-03-30 10:26 UTC
Labels: bug
